#!/bin/bash
# Step 1 — Register job in jobs.csv
# Usage: bash 01-job.sh <job_id> <source_file> <song_name>
# job_id is pre-generated by the caller (api.py or script.sh).
# status.json is written by the caller before this runs.
# This script only appends the audit log entry to jobs.csv.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../lib.sh"

JOB_ID="$1"
SOURCE_FILE="$2"
SONG_NAME="$3"

log "Step 1: registering job $JOB_ID" >&2

mkdir -p "$JOBS_DIR"

JOBS_CSV="$JOBS_DIR/jobs.csv"
[ -f "$JOBS_CSV" ] || printf "datetime,job_id,source_file\n" > "$JOBS_CSV"
echo "$(date '+%Y-%m-%d %H:%M:%S'),$JOB_ID,$SOURCE_FILE" >> "$JOBS_CSV"
